services:
  - type: web
    name: megavibe-backend
    runtime: node
    plan: starter
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: megavibe-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://megavibe.vercel.app
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_API_SECRET
        sync: false
      - key: PINATA_JWT_TOKEN
        sync: false

databases:
  - name: megavibe-mongodb
    databaseName: megavibe
    user: megavibe
